### ISSUE TITLE
Releases with the same name clobber each other

### ISSUE THREAD

**Issue by XXLuigiMario** [easlice/bandcamp-downloader#14]
I have two releases on my library which have the same name. bandcamp-downloader chooses the same filename for both and one ends up overwriting the other.

Example:
https://kissmenerdygirl.bandcamp.com/track/untitled
https://kissmenerdygirl.bandcamp.com/track/untitled-2
(they are actually different tracks)
![Screenshot from 2023-02-26 18-04-21](https://user-images.githubusercontent.com/7153662/221425104-ec95bf83-826d-48bd-8e20-949382671ea1.png)

**Comment by easlice** [comment]
This should be fixed by PR #15, so I'm closing this.
