### ISSUE TITLE
HTTP/TLS fingerprint

### ISSUE THREAD

**Issue by gkdwoe** [easlice/bandcamp-downloader#35]
In my case python requests to "https://bandcamp.com" resulted in 403 forbidden.
Using something like https://github.com/lexiforest/curl_cffi to impersonate chrome would work fine.

**Comment by easlice** [comment]
Hey @gkdwoe, did you test using curl_cffi and saw that it resolved this?

I've hit this issue from time to time too. I tried setting the `user-agent` header manually but still received the error from bandcamp's varnish cache server.

**Comment by easlice** [comment]
Nevermind, I just tried it with curl_cffi, and that does work where just setting the user agent doesn't. Odd.

It also takes a few code changes (their Request object doesn't support `with ... as ...` syntax), but I'll get a change out for this shortly.

**Comment by easlice** [comment]
@gkdwoe Can you try this again and verify that it works for you? It seems to fix the issue for me, but I would like a better sample size than 1.
