### ISSUE TITLE
Invalid characters not sanitised [WinError 123]

### ISSUE THREAD

**Issue by cyotek** [easlice/bandcamp-downloader#36]
Hello,

I'm trying to download my collection, but a number of MASTER BOOT RECORD albums are failing as their titles have characters in them that aren't valid for filenames, e.g. `C:\>COPY *.* A: /V` (yes, that is a real album name!)

I searched existing issues and found #2 which seems to have addressed this at some point but it appears to have been reintroduced.

I'm using the latest version as of 9b8a72b.

```
ERROR: An exception occurred trying to download file url [https://popplers5.bandcamp.com/download/album?XXX]:
Traceback (most recent call last):

  File "D:\Checkout\bandcamp-update\bandcamp-downloader.py", line 395, in download_file
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 223, in makedirs
    mkdir(name, mode)

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'd:\\music\\zip\\bandcamp\\aac-hi\\MASTER BOOT RECORD\\MASTER BOOT RECORD - C:'
```

Regards;
Richard Moss

**Comment by easlice** [comment]
This should be fixed now. Closing.
