### ISSUE TITLE
Feature request: a way to specify *only* Bandcamp cookies

### ISSUE THREAD

**Issue by voltagex** [easlice/bandcamp-downloader#44]
I'd like to be able to use a browser extension to dump only my Bandcamp cookies and then provide them to bandcamp-downloader

Use case: I have a headless NAS and I'd like to be able to use bandcamp-downloader on it without copying all my cookies over at once.

**Comment by easlice** [comment]
You should already be able to do that with the `--cookies` flag. It takes a standard Mozilla cookie jar file. Did that not work for you?

**Comment by voltagex** [comment]
Whoops! I was looking at browser_cookie3 which is loading files out of the Firefox profile directly.

**Comment by voltagex** [comment]
Confirming that https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/ works fine in combination with `--cookies`

Sorry about that!
